services:
  redis:
    image: redis/redis-stack
    container_name: redis
    ports:
      - "6379:6379"
      - "8001:8001"

  mongo:
    image: mongo:6.0
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongo_data:/data/db

  server:
    build:
      context: ./ecommerce-backend
      dockerfile: Dockerfile.dev
    container_name: server
    ports:
      - "4000:4000"
    env_file:
      - ./ecommerce-backend/.env
    environment:
      NODE_ENV: development
      REDIS_URL: redis://redis:6379
      MONGO_URI: mongodb://admin:password123@mongo:27017/ecom25?authSource=admin
    depends_on:
      - redis
      - mongo
    develop:
      watch:
        - path: ./ecommerce-backend/package*.json
          action: rebuild
        - path: ./ecommerce-backend
          target: /app
          action: sync

  client:
    build:
      context: ./ecommerce-frontend
      dockerfile: Dockerfile.dev
    container_name: client
    ports:
      - "5173:5173"
    env_file:
      - ./ecommerce-frontend/.env
    depends_on:
      - server
    develop:
      watch:
        - path: ./ecommerce-frontend/package*.json
          action: rebuild
        - path: ./ecommerce-frontend
          target: /app
          action: sync

volumes:
  mongo_data:
